// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5JojkHffPqZX7Qckl7ckDgF-oZG58Puc',
    appId: '1:42751085118:web:9fa2e73011781da7421f6f',
    messagingSenderId: '42751085118',
    projectId: 'todoapp-design',
    authDomain: 'todoapp-design.firebaseapp.com',
    storageBucket: 'todoapp-design.appspot.com',
    measurementId: 'G-B3LMGH25RZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzQEmG0ofRkNCkpMCY_b61rM8waKR_AsU',
    appId: '1:42751085118:android:d1997c50d3ea6e72421f6f',
    messagingSenderId: '42751085118',
    projectId: 'todoapp-design',
    storageBucket: 'todoapp-design.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIPEif8jfG5fC-UrSpuzxh_zzji_9l9ok',
    appId: '1:42751085118:ios:96caf932c7f3c5cf421f6f',
    messagingSenderId: '42751085118',
    projectId: 'todoapp-design',
    storageBucket: 'todoapp-design.appspot.com',
    iosClientId: '42751085118-ceh4t411sgufs0dmpkpr14bf0rgq580s.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIPEif8jfG5fC-UrSpuzxh_zzji_9l9ok',
    appId: '1:42751085118:ios:96caf932c7f3c5cf421f6f',
    messagingSenderId: '42751085118',
    projectId: 'todoapp-design',
    storageBucket: 'todoapp-design.appspot.com',
    iosClientId: '42751085118-ceh4t411sgufs0dmpkpr14bf0rgq580s.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );
}
